services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sampletechnology-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "YourStrong!Passw0rd"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql

  postgres:
    image: postgres:18
    container_name: sampletechnology-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: YourStrong!Passw0rd
      POSTGRES_DB: SampleTechnologyForTest
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:8-alpine
    container_name: sampletechnology-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  mongodb:
    image: mongo:8
    container_name: sampletechnology-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  restapi:
    build:
      context: .
      dockerfile: UI/SampleTechnologyForTest.RestApi/Dockerfile
    container_name: sampletechnology-restapi
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development

      ConnectionStrings__CommandDBConnection: "Server=sqlserver,1433;Database=SampleTechnologyForTest;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;"

      ConnectionStrings__QueryDBConnection: "Host=postgres;Port=5432;Database=SampleTechnologyForTest;Username=postgres;Password=YourStrong!Passw0rd;Include Error Detail=true;"

      ConnectionStrings__RedisConnection: "redis:6379"

      MongoDbSettings__ConnectionString: "mongodb://mongodb:27017"
      MongoDbSettings__DatabaseName: "SampleTechnologyForTest"

    depends_on:
      - sqlserver
      - postgres
      - redis
      - mongodb

volumes:
  sqlserver_data:
  postgres_data:
  redis_data:
  mongodb_data: